# Generated by Django 5.1.1 on 2024-10-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
